#!/bin/bash
set -eu


chown -R cloudron:cloudron /run /app/data

exec /usr/bin/supervisord --configuration /etc/supervisor/supervisord.conf --nodaemon -i calibre-web

cat <<-EOF > "/app/data/ldap_email_settings.txt"

CLOUDRON_MAIL_DOMAIN = ${CLOUDRON_MAIL_DOMAIN}
CLOUDRON_MAIL_SMTP_PORT = ${CLOUDRON_MAIL_SMTP_PORT}
CLOUDRON_MAIL_IMAP_PORT = ${CLOUDRON_MAIL_IMAP_PORT}
CLOUDRON_MAIL_SMTP_SERVER = ${CLOUDRON_MAIL_SMTP_SERVER}

--

CLOUDRON_LDAP_SERVER = ${CLOUDRON_LDAP_SERVER}
CLOUDRON_LDAP_USERS_BASE_DN = ${CLOUDRON_LDAP_USERS_BASE_DN}
CLOUDRON_LDAP_MAILBOXES_BASE_DN = ${CLOUDRON_LDAP_MAILBOXES_BASE_DN}
CLOUDRON_LDAP_GROUPS_BASE_DN = ${CLOUDRON_LDAP_GROUPS_BASE_DN}
CLOUDRON_LDAP_BIND_PASSWORD = ${CLOUDRON_LDAP_BIND_PASSWORD}
CLOUDRON_LDAP_URL = ${CLOUDRON_LDAP_URL}

CLOUDRON_LDAP_PORT = ${CLOUDRON_LDAP_PORT}
CLOUDRON_LDAP_BIND_DN = ${CLOUDRON_LDAP_BIND_DN}

EOF

